### ISSUE TITLE
Mod crashes the server on startup

### ISSUE THREAD

**Issue by DragonMadness** [lukebemishprojects/Tempest#50]
I've recently added this mod to my local server but i've been struggling to get it working. Maybe what's important here is that the world already exists and maybe it breaks trying to convert the world or something.
Here's the stack trace:
```
[22:04:39] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "dev.lukebemish.tempest.impl.data.world.LevelIdMap.id(net.minecraft.resources.ResourceKey)" because "dev.lukebemish.tempest.impl.data.world.LevelIdMap.CURRENT" is null
        at dev.lukebemish.tempest.impl.data.world.WeatherChunkData.update(WeatherChunkData.java:109) ~[tempest-forge-1.20.1-0.1.12.jar%23175!/:0.1.12] {re:mixin,re:classloading}
        at dev.lukebemish.tempest.impl.data.world.WeatherChunkData.tick(WeatherChunkData.java:302) ~[tempest-forge-1.20.1-0.1.12.jar%23175!/:0.1.12] {re:mixin,re:classloading}
        at net.minecraft.server.level.ServerLevel.handler$zha000$tempest$tickChunk(ServerLevel.java:2161) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:mixin.tempest.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:mixin.tempest.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:362) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:mixin.tempest.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23187!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        ... 5 more
```

**Comment by DragonMadness** [comment]
Also forgot to mention some system variables
```
Minecraft Version: 1.20.1
        Minecraft Version ID: 1.20.1
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 17.0.6, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
        Memory: 939851008 bytes (896 MiB) / 3443523584 bytes (3284 MiB) up to 8589934592 bytes (8192 MiB)
        CPUs: 12
        Processor Vendor: AuthenticAMD
        Processor Name: AMD Ryzen 5 3600 6-Core Processor
        Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
        Microarchitecture: Zen 2
        Frequency (GHz): 3.59
        Number of physical packages: 1
        Number of physical CPUs: 6
        Number of logical CPUs: 12
        Graphics card #0 name: Radeon RX 580 Series
        Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
        Graphics card #0 VRAM (MB): 4095.00
        Graphics card #0 deviceId: 0x67df
        Graphics card #0 versionInfo: DriverVersion=31.0.21906.6
        Memory slot #0 capacity (MB): 16384.00
        Memory slot #0 clockSpeed (GHz): 2.40
        Memory slot #0 type: DDR4
        Memory slot #1 capacity (MB): 16384.00
        Memory slot #1 clockSpeed (GHz): 2.40
        Memory slot #1 type: DDR4
        Virtual memory max (MB): 37555.80
        Virtual memory used (MB): 27127.80
        Swap memory total (MB): 4864.00
        Swap memory used (MB): 59.57
        JVM Flags: 1 total; -Xmx8G
        Server Running: true
        Player Count: 0 / 20; []
        Data Packs: vanilla, mod:bellsandwhistles, mod:betterdungeons, mod:create_things_and_misc, mod:mousetweaks, mod:betterwitchhuts, mod:geckolib, mod:jei, mod:yungsbridges, mod:betteroceanmonuments, mod:curios (incompatible), mod:create_crush_everything, mod:flywheel, mod:createoreexcavation (incompatible), mod:create, mod:createsifter (incompatible), mod:create_sa, mod:justenoughprofessions, mod:mrc, mod:yungsapi, mod:mixinextras (incompatible), mod:betterstrongholds, mod:design_decor (incompatible), mod:createcasing (incompatible), mod:snowundertrees, mod:create_dragon_lib (incompatible), mod:betterdeserttemples, mod:railways, mod:jeresources, mod:interiors (incompatible), mod:betterfortresses, mod:forge, mod:appleskin (incompatible), mod:bettermineshafts, mod:tfmg (incompatible), mod:create_enchantment_industry (incompatible), mod:create_power_loader, mod:botarium (incompatible), mod:create_new_age, mod:createdeco (incompatible), mod:create_dd (incompatible), mod:spark (incompatible), mod:elytratrims (incompatible), mod:mixinsquared (incompatible), mod:obsidianui (incompatible), mod:kotlinforforge (incompatible), mod:architectury (incompatible), mod:tempest
        Enabled Feature Flags: minecraft:vanilla
        World Generation: Experimental
        Is Modded: Definitely; Server brand changed to 'forge'
        Type: Dedicated Server (map_server.txt)
        ModLauncher: 10.0.9+10.0.9+main.dcd20f30
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                mixin-0.8.5.jar mixin PLUGINSERVICE
                eventbus-6.0.5.jar eventbus PLUGINSERVICE
                fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE
                fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE
                fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE
                fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE
                accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE
                fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE
                modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE
                modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                javafml@null
                kotlinforforge@4.10.0
                lowcodefml@null
        Mod List:
                bellsandwhistles-0.4.3-1.20.x.jar                 |Create: Bells & Whistles      |bellsandwhistles              |0.4.3-1.20.x        |DONE      |Manifest: NOSIGNATURE
                YungsBetterDungeons-1.20-Forge-4.0.4.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
                create_misc_and_things_ 1.20.1_4.0A.jar           |create: things and misc       |create_things_and_misc        |1.0.0               |DONE      |Manifest: NOSIGNATURE
                YungsBetterWitchHuts-1.20-Forge-3.0.3.jar         |YUNG's Better Witch Huts      |betterwitchhuts               |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
                Create-Dreams-n-Desires-1.20.1-0.2c.PREBETA.jar   |Create: Dreams & Desires      |create_dd                     |0.2c.PREBETA        |DONE      |Manifest: NOSIGNATURE
                geckolib-forge-1.20.1-4.4.2.jar                   |GeckoLib 4                    |geckolib                      |4.4.2               |DONE      |Manifest: NOSIGNATURE
                createdeco-2.0.2-1.20.1-forge.jar                 |Create Deco                   |createdeco                    |2.0.2-1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
                botarium-forge-1.20.1-2.3.3.jar                   |Botarium                      |botarium                      |2.3.3               |DONE      |Manifest: NOSIGNATURE
                jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
                YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |DONE      |Manifest: NOSIGNATURE
                ObsidianUI-forge-0.2.3+mc1.20.1.jar               |ObsidianUI                    |obsidianui                    |0.2.3+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
                create_recycle_1.0.2_forge_1.20.1.jar             |Create Recycling              |create_crush_everything       |1.0.2               |DONE      |Manifest: NOSIGNATURE
                YungsApi-1.20-Forge-4.0.4.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
                mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
                design_decor-0.4-1.20.1.jar                       |Create: Design n' Decor       |design_decor                  |0.4.0               |DONE      |Manifest: NOSIGNATURE
                snowundertrees-1.20.1-1.4.4.jar                   |Snow Under Trees              |snowundertrees                |1.4.4               |DONE      |Manifest: NOSIGNATURE
                create_dragon_lib-1.20.1-1.4.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.4.2               |DONE      |Manifest: NOSIGNATURE
                YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
                Steam_Rails-1.6.4+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.6.4+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
                create-new-age-forge-1.20.1-1.1.2.jar             |Create: New Age               |create_new_age                |1.1.2               |DONE      |Manifest: NOSIGNATURE
                JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |DONE      |Manifest: NOSIGNATURE
                interiors-0.5.3+forge-mc1.20.1.jar                |Create: Interiors             |interiors                     |0.5.3+forge-mc1.20.1|DONE      |Manifest: NOSIGNATURE
                YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.6    |DONE      |Manifest: NOSIGNATURE
                forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                tfmg-0.8.0b-1.20.1.jar                            |Create: The Factory Must Grow |tfmg                          |0.8.0b              |DONE      |Manifest: NOSIGNATURE
                elytratrims-forge-3.1.4+1.20.1.jar                |Elytra Trims                  |elytratrims                   |3.1.4               |DONE      |Manifest: NOSIGNATURE
                server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
                MouseTweaks-forge-mc1.20-2.25.jar                 |Mouse Tweaks                  |mousetweaks                   |2.25                |DONE      |Manifest: NOSIGNATURE
                mixinsquared-forge-0.1.2-beta.4.jar               |MixinSquared                  |mixinsquared                  |0.1.2-beta.4        |DONE      |Manifest: NOSIGNATURE
                YungsBridges-1.20-Forge-4.0.3.jar                 |YUNG's Bridges                |yungsbridges                  |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
                tempest-forge-1.20.1-0.1.12.jar                   |Tempest                       |tempest                       |0.1.12              |DONE      |Manifest: NOSIGNATURE
                spark-1.10.53-forge.jar                           |spark                         |spark                         |1.10.53             |DONE      |Manifest: NOSIGNATURE
                kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
                curios-forge-5.9.0+1.20.1.jar                     |Curios API                    |curios                        |5.9.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
                flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
                create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
                CreateCasing-1.20.1-1.6.0.jar                     |Create : Encased              |createcasing                  |1.20.1-1.6.0        |DONE      |Manifest: NOSIGNATURE
                createsifter-1.20.1-1.8.1.e-22.jar                |Create Sifter                 |createsifter                  |1.20.1-1.8.1.e-22   |DONE      |Manifest: NOSIGNATURE
                createoreexcavation-1.20-1.4.3.jar                |Create Ore Excavation         |createoreexcavation           |1.4.3               |DONE      |Manifest: NOSIGNATURE
                create-stuff-additions1.20.1_v2.0.4a.jar          |Create Stuff & Additions      |create_sa                     |2.0.4.              |DONE      |Manifest: NOSIGNATURE
                JustEnoughProfessions-forge-1.20.1-3.0.1.jar      |Just Enough Professions (JEP) |justenoughprofessions         |3.0.1               |DONE      |Manifest: NOSIGNATURE
                mcr-v2.1.jar                                      |more_recycling_create         |mrc                           |1.0.0               |DONE      |Manifest: NOSIGNATURE
                YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
                architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
                appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
                create_power_loader-1.4.0-mc1.20.1.jar            |Create: Power Loader          |create_power_loader           |1.4.0-mc1.20.1      |DONE      |Manifest: NOSIGNATURE
                YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
                create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.9.c             |DONE      |Manifest: NOSIGNATURE
        Crash Report UUID: e21a18b3-4db4-4c66-9b87-2fa7cb9cc99f
        FML: 47.2
        Forge: net.minecraftforge:47.2.0
```

**Comment by lukebemish** [comment]
Hmm... I wonder if something changed with event timings or something before mcforge 47.2. I'll give it a poke; thanks for letting me know

**Comment by lukebemish** [comment]
Can you share a full log, not just the crash report?

**Comment by lukebemish** [comment]
Fixed in the new release, which is currently publishing
